// Node sub-types with icons for each FlowNodeType

import type { FlowNodeType } from './flow-types'

export interface NodeVariant {
  readonly id: string
  readonly label: string
  readonly emoji: string
  readonly icon?: string // path to /icons/{id}.png
}

export const NODE_VARIANTS: Record<FlowNodeType, readonly NodeVariant[]> = {
  traffic_source: [
    { id: 'facebook', label: 'Facebook Ads', emoji: 'f', icon: '/icons/facebook.png' },
    { id: 'google', label: 'Google Ads', emoji: 'G', icon: '/icons/google.png' },
    { id: 'tiktok', label: 'TikTok', emoji: 'T', icon: '/icons/tiktok.png' },
    { id: 'instagram', label: 'Instagram', emoji: 'I', icon: '/icons/instagram.png' },
    { id: 'youtube', label: 'YouTube', emoji: 'Y', icon: '/icons/youtube.png' },
    { id: 'linkedin', label: 'LinkedIn', emoji: 'in', icon: '/icons/linkedin.png' },
    { id: 'twitter', label: 'X / Twitter', emoji: 'X', icon: '/icons/twitter.png' },
    { id: 'reddit', label: 'Reddit', emoji: 'R', icon: '/icons/reddit.png' },
    { id: 'email_blast', label: 'Email Blast', emoji: '@', icon: '/icons/email_blast.png' },
    { id: 'seo', label: 'Organic / SEO', emoji: 'S', icon: '/icons/seo.png' },
    { id: 'referral', label: 'Referral', emoji: 'R', icon: '/icons/referral.png' },
    { id: 'direct', label: 'Direct Traffic', emoji: 'D', icon: '/icons/direct.png' },
    { id: 'podcast', label: 'Podcast', emoji: 'P', icon: '/icons/podcast.png' },
    { id: 'affiliate', label: 'Affiliate', emoji: 'A', icon: '/icons/affiliate.png' },
    { id: 'pr', label: 'PR / Press', emoji: 'P', icon: '/icons/pr.png' },
    { id: 'qr', label: 'QR Code', emoji: 'Q', icon: '/icons/qr.png' },
    { id: 'cold_call', label: 'Cold Call', emoji: 'C', icon: '/icons/cold_call.png' },
    { id: 'cold_email', label: 'Cold Email', emoji: 'E', icon: '/icons/cold_email.png' },
    { id: 'billboard', label: 'Billboard / OOH', emoji: 'B', icon: '/icons/billboard.png' },
    { id: 'event', label: 'Event / Trade Show', emoji: 'E', icon: '/icons/event.png' },
    { id: 'webinar_promo', label: 'Webinar Promo', emoji: 'W', icon: '/icons/webinar_promo.png' },
    { id: 'sms', label: 'SMS', emoji: 'S', icon: '/icons/sms.png' },
    { id: 'push', label: 'Push Notification', emoji: 'N', icon: '/icons/push.png' },
  ],
  landing_page: [
    { id: 'hero', label: 'Hero Landing', emoji: 'H' },
    { id: 'longform', label: 'Long-form Sales', emoji: 'L' },
    { id: 'squeeze', label: 'Squeeze Page', emoji: 'S' },
    { id: 'video', label: 'Video Landing', emoji: 'V' },
    { id: 'webinar_reg', label: 'Webinar Registration', emoji: 'W' },
    { id: 'product', label: 'Product Page', emoji: 'P' },
    { id: 'comparison', label: 'Comparison Page', emoji: 'C' },
    { id: 'waitlist', label: 'Waitlist', emoji: 'W' },
    { id: 'coming_soon', label: 'Coming Soon', emoji: 'C' },
  ],
  opt_in_form: [
    { id: 'popup', label: 'Popup Modal', emoji: 'P' },
    { id: 'inline', label: 'Inline Form', emoji: 'I' },
    { id: 'slide_in', label: 'Slide-in', emoji: 'S' },
    { id: 'exit_intent', label: 'Exit Intent', emoji: 'X' },
    { id: 'quiz', label: 'Quiz / Survey', emoji: 'Q' },
    { id: 'lead_magnet', label: 'Lead Magnet', emoji: 'L' },
    { id: 'free_tool', label: 'Free Tool', emoji: 'T' },
    { id: 'calculator', label: 'Calculator', emoji: 'C' },
    { id: 'chatbot', label: 'Chatbot Capture', emoji: 'B' },
  ],
  sales_page: [
    { id: 'vsl', label: 'Video Sales Letter', emoji: 'V' },
    { id: 'longform_sales', label: 'Long-form Copy', emoji: 'L' },
    { id: 'case_study', label: 'Case Study', emoji: 'C' },
    { id: 'testimonial', label: 'Testimonial Page', emoji: 'T' },
    { id: 'demo', label: 'Live Demo', emoji: 'D' },
    { id: 'pricing_page', label: 'Pricing Page', emoji: '$' },
    { id: 'proposal', label: 'Proposal / Quote', emoji: 'P' },
    { id: 'booking', label: 'Booking / Calendar', emoji: 'B' },
  ],
  upsell: [
    { id: 'one_click', label: 'One-Click Upsell', emoji: '1' },
    { id: 'order_bump', label: 'Order Bump', emoji: '+' },
    { id: 'post_purchase', label: 'Post-Purchase', emoji: 'P' },
    { id: 'bundle_offer', label: 'Bundle Offer', emoji: 'B' },
    { id: 'annual_upgrade', label: 'Annual Upgrade', emoji: 'A' },
    { id: 'premium_tier', label: 'Premium Tier', emoji: 'P' },
    { id: 'add_on', label: 'Add-on', emoji: '+' },
  ],
  downsell: [
    { id: 'lite', label: 'Lite Version', emoji: 'L' },
    { id: 'payment_plan', label: 'Payment Plan', emoji: 'P' },
    { id: 'trial_extend', label: 'Extended Trial', emoji: 'T' },
    { id: 'smaller_package', label: 'Smaller Package', emoji: 'S' },
    { id: 'free_tier', label: 'Free Tier', emoji: 'F' },
  ],
  email_sequence: [
    { id: 'welcome', label: 'Welcome Series', emoji: 'W' },
    { id: 'nurture', label: 'Nurture Sequence', emoji: 'N' },
    { id: 'launch', label: 'Launch Sequence', emoji: 'L' },
    { id: 'cart_abandon', label: 'Cart Abandonment', emoji: 'C' },
    { id: 'reengagement', label: 'Re-engagement', emoji: 'R' },
    { id: 'onboarding', label: 'Onboarding Drip', emoji: 'O' },
    { id: 'winback', label: 'Win-back', emoji: 'W' },
    { id: 'upsell_drip', label: 'Upsell Drip', emoji: 'U' },
    { id: 'webinar_replay', label: 'Webinar Follow-up', emoji: 'F' },
  ],
  checkout: [
    { id: 'single_page', label: 'Single Page', emoji: '1' },
    { id: 'multi_step', label: 'Multi-step', emoji: 'M' },
    { id: 'one_click_buy', label: 'One-Click Buy', emoji: '1' },
    { id: 'free_trial', label: 'Free Trial Signup', emoji: 'F' },
    { id: 'subscription', label: 'Subscription', emoji: 'S' },
    { id: 'invoice', label: 'Invoice / Quote', emoji: 'I' },
    { id: 'stripe_link', label: 'Payment Link', emoji: 'L' },
  ],
  thank_you: [
    { id: 'confirmation', label: 'Confirmation', emoji: 'C' },
    { id: 'upsell_offer', label: 'Upsell Offer', emoji: 'U' },
    { id: 'survey', label: 'Feedback Survey', emoji: 'S' },
    { id: 'referral_ask', label: 'Referral Ask', emoji: 'R' },
    { id: 'next_steps', label: 'Next Steps', emoji: 'N' },
    { id: 'community', label: 'Join Community', emoji: 'C' },
    { id: 'share', label: 'Social Share', emoji: 'S' },
  ],
  custom: [
    { id: 'custom', label: 'Custom Step', emoji: '?' },
    { id: 'api_call', label: 'API / Webhook', emoji: 'A' },
    { id: 'wait', label: 'Wait / Delay', emoji: 'W' },
    { id: 'condition', label: 'Condition / Split', emoji: 'C' },
    { id: 'crm_update', label: 'CRM Update', emoji: 'C' },
    { id: 'tag', label: 'Tag / Label', emoji: 'T' },
    { id: 'notification', label: 'Internal Alert', emoji: 'N' },
    { id: 'manual_review', label: 'Manual Review', emoji: 'M' },
  ],
}
