// Node sub-types with icons for each FlowNodeType

import type { FlowNodeType } from './flow-types'

export interface NodeVariant {
  readonly id: string
  readonly label: string
  readonly emoji: string
  readonly icon?: string // path to /icons/{id}.png
}

export const NODE_VARIANTS: Record<FlowNodeType, readonly NodeVariant[]> = {
  traffic_source: [
    { id: 'facebook', label: 'Facebook Ads', emoji: 'f', icon: '/icons/facebook.png' },
    { id: 'google', label: 'Google Ads', emoji: 'G', icon: '/icons/google.png' },
    { id: 'tiktok', label: 'TikTok', emoji: 'T', icon: '/icons/tiktok.png' },
    { id: 'instagram', label: 'Instagram', emoji: 'I', icon: '/icons/instagram.png' },
    { id: 'youtube', label: 'YouTube', emoji: 'Y', icon: '/icons/youtube.png' },
    { id: 'linkedin', label: 'LinkedIn', emoji: 'in', icon: '/icons/linkedin.png' },
    { id: 'twitter', label: 'X / Twitter', emoji: 'X', icon: '/icons/twitter.png' },
    { id: 'reddit', label: 'Reddit', emoji: 'R', icon: '/icons/reddit.png' },
    { id: 'email_blast', label: 'Email Blast', emoji: '@', icon: '/icons/email_blast.png' },
    { id: 'seo', label: 'Organic / SEO', emoji: 'S', icon: '/icons/seo.png' },
    { id: 'referral', label: 'Referral', emoji: 'R', icon: '/icons/referral.png' },
    { id: 'direct', label: 'Direct Traffic', emoji: 'D', icon: '/icons/direct.png' },
    { id: 'podcast', label: 'Podcast', emoji: 'P', icon: '/icons/podcast.png' },
    { id: 'affiliate', label: 'Affiliate', emoji: 'A', icon: '/icons/affiliate.png' },
    { id: 'pr', label: 'PR / Press', emoji: 'P', icon: '/icons/pr.png' },
    { id: 'qr', label: 'QR Code', emoji: 'Q', icon: '/icons/qr.png' },
    { id: 'cold_call', label: 'Cold Call', emoji: 'C', icon: '/icons/cold_call.png' },
    { id: 'cold_email', label: 'Cold Email', emoji: 'E', icon: '/icons/cold_email.png' },
    { id: 'billboard', label: 'Billboard / OOH', emoji: 'B', icon: '/icons/billboard.png' },
    { id: 'event', label: 'Event / Trade Show', emoji: 'E', icon: '/icons/event.png' },
    { id: 'webinar_promo', label: 'Webinar Promo', emoji: 'W', icon: '/icons/webinar_promo.png' },
    { id: 'sms', label: 'SMS', emoji: 'S', icon: '/icons/sms.png' },
    { id: 'push', label: 'Push Notification', emoji: 'N', icon: '/icons/push.png' },
  ],
  landing_page: [
    { id: 'hero', label: 'Hero Landing', emoji: 'H' },
    { id: 'longform', label: 'Long-form Sales', emoji: 'L' },
    { id: 'squeeze', label: 'Squeeze Page', emoji: 'S' },
    { id: 'video', label: 'Video Landing', emoji: 'V' },
    { id: 'webinar_reg', label: 'Webinar Registration', emoji: 'W' },
    { id: 'product', label: 'Product Page', emoji: 'P' },
    { id: 'comparison', label: 'Comparison Page', emoji: 'C' },
    { id: 'waitlist', label: 'Waitlist', emoji: 'W' },
    { id: 'coming_soon', label: 'Coming Soon', emoji: 'C' },
  ],
  opt_in_form: [
    { id: 'popup', label: 'Popup Modal', emoji: 'P' },
    { id: 'inline', label: 'Inline Form', emoji: 'I' },
    { id: 'slide_in', label: 'Slide-in', emoji: 'S' },
    { id: 'exit_intent', label: 'Exit Intent', emoji: 'X' },
    { id: 'quiz', label: 'Quiz / Survey', emoji: 'Q' },
    { id: 'lead_magnet', label: 'Lead Magnet', emoji: 'L' },
    { id: 'free_tool', label: 'Free Tool', emoji: 'T' },
    { id: 'calculator', label: 'Calculator', emoji: 'C' },
    { id: 'chatbot', label: 'Chatbot Capture', emoji: 'B' },
  ],
  sales_page: [
    { id: 'vsl', label: 'Video Sales Letter', emoji: 'V' },
    { id: 'longform_sales', label: 'Long-form Copy', emoji: 'L' },
    { id: 'case_study', label: 'Case Study', emoji: 'C' },
    { id: 'testimonial', label: 'Testimonial Page', emoji: 'T' },
    { id: 'demo', label: 'Live Demo', emoji: 'D' },
    { id: 'pricing_page', label: 'Pricing Page', emoji: '$' },
    { id: 'proposal', label: 'Proposal / Quote', emoji: 'P' },
    { id: 'booking', label: 'Booking / Calendar', emoji: 'B' },
  ],
  upsell: [
    { id: 'one_click', label: 'One-Click Upsell', emoji: '1' },
    { id: 'order_bump', label: 'Order Bump', emoji: '+' },
    { id: 'post_purchase', label: 'Post-Purchase', emoji: 'P' },
    { id: 'bundle_offer', label: 'Bundle Offer', emoji: 'B' },
    { id: 'annual_upgrade', label: 'Annual Upgrade', emoji: 'A' },
    { id: 'premium_tier', label: 'Premium Tier', emoji: 'P' },
    { id: 'add_on', label: 'Add-on', emoji: '+' },
  ],
  downsell: [
    { id: 'lite', label: 'Lite Version', emoji: 'L' },
    { id: 'payment_plan', label: 'Payment Plan', emoji: 'P' },
    { id: 'trial_extend', label: 'Extended Trial', emoji: 'T' },
    { id: 'smaller_package', label: 'Smaller Package', emoji: 'S' },
    { id: 'free_tier', label: 'Free Tier', emoji: 'F' },
  ],
  email_sequence: [
    { id: 'welcome', label: 'Welcome Series', emoji: 'W' },
    { id: 'nurture', label: 'Nurture Sequence', emoji: 'N' },
    { id: 'launch', label: 'Launch Sequence', emoji: 'L' },
    { id: 'cart_abandon', label: 'Cart Abandonment', emoji: 'C' },
    { id: 'reengagement', label: 'Re-engagement', emoji: 'R' },
    { id: 'onboarding', label: 'Onboarding Drip', emoji: 'O' },
    { id: 'winback', label: 'Win-back', emoji: 'W' },
    { id: 'upsell_drip', label: 'Upsell Drip', emoji: 'U' },
    { id: 'webinar_replay', label: 'Webinar Follow-up', emoji: 'F' },
  ],
  checkout: [
    { id: 'single_page', label: 'Single Page', emoji: '1' },
    { id: 'multi_step', label: 'Multi-step', emoji: 'M' },
    { id: 'one_click_buy', label: 'One-Click Buy', emoji: '1' },
    { id: 'free_trial', label: 'Free Trial Signup', emoji: 'F' },
    { id: 'subscription', label: 'Subscription', emoji: 'S' },
    { id: 'invoice', label: 'Invoice / Quote', emoji: 'I' },
    { id: 'stripe_link', label: 'Payment Link', emoji: 'L' },
  ],
  thank_you: [
    { id: 'confirmation', label: 'Confirmation', emoji: 'C' },
    { id: 'upsell_offer', label: 'Upsell Offer', emoji: 'U' },
    { id: 'survey', label: 'Feedback Survey', emoji: 'S' },
    { id: 'referral_ask', label: 'Referral Ask', emoji: 'R' },
    { id: 'next_steps', label: 'Next Steps', emoji: 'N' },
    { id: 'community', label: 'Join Community', emoji: 'C' },
    { id: 'share', label: 'Social Share', emoji: 'S' },
  ],
  custom: [
    { id: 'custom', label: 'Custom Step', emoji: '?' },
    { id: 'api_call', label: 'API / Webhook', emoji: 'A' },
    { id: 'wait', label: 'Wait / Delay', emoji: 'W' },
    { id: 'condition', label: 'Condition / Split', emoji: 'C' },
    { id: 'crm_update', label: 'CRM Update', emoji: 'C' },
    { id: 'tag', label: 'Tag / Label', emoji: 'T' },
    { id: 'notification', label: 'Internal Alert', emoji: 'N' },
    { id: 'manual_review', label: 'Manual Review', emoji: 'M' },
  ],
  phone_call: [
    { id: 'cold_outbound', label: 'Cold Outbound', emoji: 'C' },
    { id: 'warm_followup', label: 'Warm Follow-up', emoji: 'W' },
    { id: 'appointment_set', label: 'Appointment Setting', emoji: 'A' },
    { id: 'confirmation_call', label: 'Confirmation Call', emoji: 'C' },
  ],
  sms_outbound: [
    { id: 'promo_sms', label: 'Promotional SMS', emoji: 'P' },
    { id: 'reminder_sms', label: 'Reminder / Follow-up', emoji: 'R' },
    { id: 'two_way_sms', label: 'Two-Way Conversation', emoji: '2' },
  ],
  direct_mail: [
    { id: 'postcard', label: 'Postcard', emoji: 'P' },
    { id: 'letter', label: 'Letter', emoji: 'L' },
    { id: 'package', label: 'Package / Kit', emoji: 'K' },
    { id: 'catalog', label: 'Catalog', emoji: 'C' },
  ],
  sales_call: [
    { id: 'discovery', label: 'Discovery Call', emoji: 'D' },
    { id: 'qualification', label: 'Qualification Call', emoji: 'Q' },
    { id: 'closing', label: 'Closing Call', emoji: 'C' },
    { id: 'account_review', label: 'Account Review', emoji: 'A' },
  ],
  demo: [
    { id: 'live_demo', label: 'Live Demo', emoji: 'L' },
    { id: 'recorded_demo', label: 'Recorded Demo', emoji: 'R' },
    { id: 'product_tour', label: 'Product Tour', emoji: 'T' },
    { id: 'poc', label: 'Proof of Concept', emoji: 'P' },
  ],
  proposal: [
    { id: 'formal_proposal', label: 'Formal Proposal', emoji: 'F' },
    { id: 'quote', label: 'Quick Quote', emoji: 'Q' },
    { id: 'sow', label: 'Statement of Work', emoji: 'S' },
    { id: 'estimate', label: 'Estimate', emoji: 'E' },
  ],
  contract: [
    { id: 'standard', label: 'Standard Contract', emoji: 'S' },
    { id: 'msa', label: 'MSA + SOW', emoji: 'M' },
    { id: 'esign', label: 'E-Sign (DocuSign)', emoji: 'E' },
    { id: 'po', label: 'Purchase Order', emoji: 'P' },
  ],
  webinar: [
    { id: 'live_webinar', label: 'Live Webinar', emoji: 'L' },
    { id: 'automated_webinar', label: 'Automated / Evergreen', emoji: 'A' },
    { id: 'workshop', label: 'Workshop', emoji: 'W' },
    { id: 'masterclass', label: 'Masterclass', emoji: 'M' },
  ],
  lead_magnet: [
    { id: 'ebook', label: 'eBook / Guide', emoji: 'E' },
    { id: 'checklist', label: 'Checklist', emoji: 'C' },
    { id: 'template', label: 'Template / Swipe File', emoji: 'T' },
    { id: 'report', label: 'Report / Research', emoji: 'R' },
    { id: 'free_tool', label: 'Free Tool', emoji: 'F' },
    { id: 'calculator', label: 'Calculator', emoji: 'C' },
  ],
  video: [
    { id: 'vsl', label: 'Video Sales Letter', emoji: 'V' },
    { id: 'explainer', label: 'Explainer Video', emoji: 'E' },
    { id: 'testimonial_vid', label: 'Testimonial Video', emoji: 'T' },
    { id: 'demo_video', label: 'Demo Video', emoji: 'D' },
    { id: 'case_study_vid', label: 'Case Study Video', emoji: 'C' },
  ],
  blog_post: [
    { id: 'seo_article', label: 'SEO Article', emoji: 'S' },
    { id: 'case_study', label: 'Case Study', emoji: 'C' },
    { id: 'comparison', label: 'Comparison Post', emoji: 'V' },
    { id: 'how_to', label: 'How-To Guide', emoji: 'H' },
  ],
  delay: [
    { id: 'time_delay', label: 'Time Delay', emoji: 'T' },
    { id: 'wait_for_event', label: 'Wait for Event', emoji: 'E' },
    { id: 'business_hours', label: 'Business Hours Only', emoji: 'B' },
  ],
  condition: [
    { id: 'if_then', label: 'If / Then', emoji: 'I' },
    { id: 'ab_split', label: 'A/B Split', emoji: 'A' },
    { id: 'score_based', label: 'Score-Based Route', emoji: 'S' },
    { id: 'tag_check', label: 'Tag Check', emoji: 'T' },
  ],
  webhook: [
    { id: 'api_post', label: 'API POST', emoji: 'P' },
    { id: 'zapier', label: 'Zapier / Make', emoji: 'Z' },
    { id: 'slack_notify', label: 'Slack Notification', emoji: 'S' },
  ],
  crm_update: [
    { id: 'update_contact', label: 'Update Contact', emoji: 'U' },
    { id: 'create_deal', label: 'Create Deal', emoji: 'D' },
    { id: 'move_stage', label: 'Move Pipeline Stage', emoji: 'M' },
    { id: 'add_tag', label: 'Add Tag', emoji: 'T' },
  ],
  onboarding: [
    { id: 'welcome_email', label: 'Welcome Email', emoji: 'W' },
    { id: 'kickoff_call', label: 'Kickoff Call', emoji: 'K' },
    { id: 'self_serve', label: 'Self-Serve Setup', emoji: 'S' },
    { id: 'guided_tour', label: 'Guided Tour', emoji: 'G' },
  ],
  survey: [
    { id: 'nps', label: 'NPS Survey', emoji: 'N' },
    { id: 'csat', label: 'CSAT Survey', emoji: 'C' },
    { id: 'feedback', label: 'Product Feedback', emoji: 'F' },
    { id: 'exit_survey', label: 'Exit Survey', emoji: 'E' },
  ],
  referral_program: [
    { id: 'refer_friend', label: 'Refer a Friend', emoji: 'R' },
    { id: 'affiliate_prog', label: 'Affiliate Program', emoji: 'A' },
    { id: 'review_request', label: 'Review Request', emoji: 'R' },
    { id: 'testimonial_req', label: 'Testimonial Request', emoji: 'T' },
  ],
  renewal: [
    { id: 'auto_renew', label: 'Auto-Renewal', emoji: 'A' },
    { id: 'renewal_email', label: 'Renewal Reminder', emoji: 'R' },
    { id: 'expansion', label: 'Expansion / Upgrade', emoji: 'E' },
    { id: 'winback', label: 'Win-Back Campaign', emoji: 'W' },
  ],
}
